defmodule HL7.V2_5_1.Segments.OM1 do
  @moduledoc false

  require Logger
  alias HL7.V2_5_1.{DataTypes}

  use HL7.Segment,
    fields: [
      segment: nil,
      sequence_number_test_observation_master_file: nil,
      producers_service_test_observation_id: DataTypes.Ce,
      permitted_data_types: nil,
      specimen_required: nil,
      producer_id: DataTypes.Ce,
      observation_description: nil,
      other_service_test_observation_ids_for_the_observation: DataTypes.Ce,
      other_names: nil,
      preferred_report_name_for_the_observation: nil,
      preferred_short_name_or_mnemonic_for_observation: nil,
      preferred_long_name_for_the_observation: nil,
      orderability: nil,
      identity_of_instrument_used_to_perform_this_study: DataTypes.Ce,
      coded_representation_of_method: DataTypes.Ce,
      portable_device_indicator: nil,
      observation_producing_department_section: DataTypes.Ce,
      telephone_number_of_section: DataTypes.Xtn,
      nature_of_service_test_observation: nil,
      report_subheader: DataTypes.Ce,
      report_display_order: nil,
      date_time_stamp_for_any_change_in_definition_for_the_observation: DataTypes.Ts,
      effective_date_time_of_change: DataTypes.Ts,
      typical_turn_around_time: nil,
      processing_time: nil,
      processing_priority: nil,
      reporting_priority: nil,
      outside_sites_where_observation_may_be_performed: DataTypes.Ce,
      address_of_outside_sites: DataTypes.Xad,
      phone_number_of_outside_site: DataTypes.Xtn,
      confidentiality_code: DataTypes.Cwe,
      observations_required_to_interpret_the_observation: DataTypes.Ce,
      interpretation_of_observations: nil,
      contraindications_to_observations: DataTypes.Ce,
      reflex_tests_observations: DataTypes.Ce,
      rules_that_trigger_reflex_testing: nil,
      fixed_canned_message: DataTypes.Ce,
      patient_preparation: nil,
      procedure_medication: DataTypes.Ce,
      factors_that_may_affect_the_observation: nil,
      service_test_observation_performance_schedule: nil,
      description_of_test_methods: nil,
      kind_of_quantity_observed: DataTypes.Ce,
      point_versus_interval: DataTypes.Ce,
      challenge_information: nil,
      relationship_modifier: DataTypes.Ce,
      target_anatomic_site_of_test: DataTypes.Ce,
      modality_of_imaging_measurement: DataTypes.Ce
    ]
end
